#微信
wx:
  miniapp:
    #App ID (智能小程序ID)
    appid: wxf5e30fd3cb6f3030
    #app secret
    secret: beb40e27500acbb1f37487b377d23ad2
    #App Key
    aesKey: FKdrlMtsA7eGRmHcqvaABFmxIISyQf4r
#头条
toutiao:
  miniapp:
    #App ID (智能小程序ID)
    appid: tt5a2c2c91c50628e8
    #app secret
    secret: 5c8930253aee3e422ff37b94f2cf5911b7814bc7
