#微信小程序开发
wx:
  miniapp:
    appid: wxb34ae4090652a792     #微信小 程序的appid
    secret: 77f9060c56c93b13000a6fcd59bab521   #微信小程序的Secret
    token:
    aesKey:
    msgDataFormat: JSON
#头条小程序开发
toutiao:
  miniapp:
    appid: tt6d481bf5f2624129
    secret: 020c16626260c48f65f1ab4de0fd9ed8812bd74e
    token:
    aesKey:
    msgDataFormat: JSON
#腾讯手Q小程序开发
tencentgame:
  miniapp:
    appid: 1110086607
    secret: 2aS9otgqjutiGHty
    token: #微信小程序消息服务器配置的token
    aesKey:  #微信小程序消息服务器配置的EncodingAESKey
    msgDataFormat: JSON
#oppo小程序开发
oppogame:
  miniapp:
    pkgName: com.xmcc.nearme.gamecente #oppe需要包名
    appid: 30257039
    secret:  63C9988cD41d886c289D28A63dCE31de
    appkey:  8V6LziAbzdgc4ggw04w484OSK
    version: 1.0.0