server:
  port: 4836
  socket-port: 40001
  socket-uri: /chaochong
chaoChong.package: com.teeqee.spring.dispatcher.impl
#spring  全局消息配置
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true #  返回 时间戳
    # date-format: yyyy-MM-dd HH:mm:ss    格式化
    # time-zone: GMT+8
    time-zone: GMT+8
  profiles:
    active: dev,pass
mybatis:
  typeAliasesPackage: com.teeqee.mybatis.pojo
  mapperLocations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 空字段不返回
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true
#mybatis分页插件  2019年10月26日13:15:33
# pagehelper:
#   helperDialect: mysql
#   reasonable: true
#   supportMethodsArguments: true
#   params: count,countSql